# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuelog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Issue', verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='issuelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
