# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=1, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
