# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('product owner', 'Product Owner')], max_length=255, verbose_name='Role'),
        ),
    ]
