# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170121_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuelog',
            old_name='time',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='issuelog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='issuelog',
            name='data',
        ),
        migrations.AddField(
            model_name='issuelog',
            name='labor_costs',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(240)], verbose_name='Labor costs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuelog',
            name='note',
            field=models.TextField(default=1, verbose_name='Note'),
            preserve_default=False,
        ),
    ]
