# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20170121_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.AlterField(
            model_name='issue',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_user', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
