# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
